image: node:10.15.3

pipelines:
  default:
    - step:
        name: Build Application
        caches:
          - node
        script:
          - npm install
    - step:
        name: Create artifact
        script:
          - npm pack
  branches:
    master:
      - step:
          name: Deploy to Heroku
          deployment: test
          script:
          - pipe: atlassian/heroku-deploy:1.1.2
            variables:
              HEROKU_API_KEY: "1a1f8db6-7c20-44e5-94a8-200f4bc03193"
              HEROKU_APP_NAME: "angular-novus"
              ZIP_FILE: "novus-0.0.2.tgz"
