image: node:10.15.3

pipelines:
  default:
    - step:
        name: Build Application
        caches:
          - node
        script:
          - npm install
    - step:
        name: Create artifact
        script:
          - npm pack
    - step:
        name: Deploy to Heroku
        deployment: test
        script:
          - git push -f https://heroku:1a1f8db6-7c20-44e5-94a8-200f4bc03193@git.heroku.com/angular-novus.git