image: node:10.15.3

pipelines:
  default:
    - step:
        name: Heroku Deploy
        deployment: Deploy to development
        caches:
          - node
        script:
          - npm install
          - npm install -g @angular/cli
          - ng build --aot --prod
          - pipe: atlassian/heroku-deploy:1.1.2 
            variables: 
              HEROKU_API_KEY: '1a1f8db6-7c20-44e5-94a8-200f4bc03193' 
              HEROKU_APP_NAME: 'angular-novus' 
              ZIP_FILE: 'angular-novus.tgz'
              WAIT: 'true'
