# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.3

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - npm install
          - npm test
  branches:
    master:
      - step:
        name: Build Heroku
        script:
          - ng build --aot --prod
      - step:
        - pipe: atlassian/heroku-deploy:1.1.2 
        - variables: 
            HEROKU_API_KEY: '1a1f8db6-7c20-44e5-94a8-200f4bc03193' 
            HEROKU_APP_NAME: 'angular-novus' 
            ZIP_FILE: 'angular-novus'
